-- MySQL Script generated by MySQL Workbench
-- Sun Apr  2 14:44:16 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sjukhus
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sjukhus
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sjukhus` DEFAULT CHARACTER SET utf8 ;
USE `sjukhus` ;

-- -----------------------------------------------------
-- Table `sjukhus`.`Lakare`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sjukhus`.`Lakare` (
  `idLakare` INT(11) NOT NULL AUTO_INCREMENT,
  `namn` VARCHAR(45) NOT NULL,
  `efternamn` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLakare`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sjukhus`.`Patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sjukhus`.`Patient` (
  `idPatient` INT(11) NOT NULL AUTO_INCREMENT,
  `namn` VARCHAR(45) NOT NULL,
  `efternamn` VARCHAR(45) NOT NULL,
  `Lakare_idLakare` INT(11) NOT NULL,
  PRIMARY KEY (`idPatient`),
  INDEX `fk_Patient_Lakare1_idx` (`Lakare_idLakare` ASC),
  CONSTRAINT `fk_Patient_Lakare1`
    FOREIGN KEY (`Lakare_idLakare`)
    REFERENCES `sjukhus`.`Lakare` (`idLakare`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sjukhus`.`Medicin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sjukhus`.`Medicin` (
  `idMedicin` INT(11) NOT NULL AUTO_INCREMENT,
  `medicin_namn` VARCHAR(225) NOT NULL,
  `medicin_doz` INT(11) NOT NULL,
  PRIMARY KEY (`idMedicin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sjukhus`.`Diagnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sjukhus`.`Diagnos` (
  `idDiagnos` INT(11) NOT NULL AUTO_INCREMENT,
  `diagnos_namn` VARCHAR(255) NOT NULL,
  `diagnos_kategori` VARCHAR(45) NOT NULL,
  `idMedicin` INT(11) NOT NULL,
  PRIMARY KEY (`idDiagnos`),
  INDEX `fk_Diagnos_Medicin1_idx` (`idMedicin` ASC),
  CONSTRAINT `fk_Diagnos_Medicin1`
    FOREIGN KEY (`idMedicin`)
    REFERENCES `sjukhus`.`Medicin` (`idMedicin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sjukhus`.`Skoterska`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sjukhus`.`Skoterska` (
  `idSkoterska` INT(11) NOT NULL AUTO_INCREMENT,
  `namn` VARCHAR(45) NOT NULL,
  `efternamn` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSkoterska`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sjukhus`.`Patient_has_Diagnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sjukhus`.`Patient_has_Diagnos` (
  `idPatient` INT(11) NOT NULL,
  `idDiagnos` INT(11) NOT NULL,
  PRIMARY KEY (`idPatient`, `idDiagnos`),
  INDEX `fk_Patient_has_Diagnos_Diagnos1_idx` (`idDiagnos` ASC),
  INDEX `fk_Patient_has_Diagnos_Patient1_idx` (`idPatient` ASC),
  CONSTRAINT `fk_Patient_has_Diagnos_Patient1`
    FOREIGN KEY (`idPatient`)
    REFERENCES `sjukhus`.`Patient` (`idPatient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Patient_has_Diagnos_Diagnos1`
    FOREIGN KEY (`idDiagnos`)
    REFERENCES `sjukhus`.`Diagnos` (`idDiagnos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sjukhus`.`Patient_Skoterska`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sjukhus`.`Patient_Skoterska` (
  `idPatient` INT(11) NOT NULL,
  `idSkoterska` INT(11) NOT NULL,
  PRIMARY KEY (`idPatient`, `idSkoterska`),
  INDEX `fk_Patient_has_Skoterska_Skoterska1_idx` (`idSkoterska` ASC),
  INDEX `fk_Patient_has_Skoterska_Patient1_idx` (`idPatient` ASC),
  CONSTRAINT `fk_Patient_has_Skoterska_Patient1`
    FOREIGN KEY (`idPatient`)
    REFERENCES `sjukhus`.`Patient` (`idPatient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Patient_has_Skoterska_Skoterska1`
    FOREIGN KEY (`idSkoterska`)
    REFERENCES `sjukhus`.`Skoterska` (`idSkoterska`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
